# .github/workflows/docker/docker-build.yml
name: Build Docker Image

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      app-name:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }} # O la versión que necesites
      - name: Get version from package.json
        id: get_version
        run: echo "VERSION=$(node -p -e \"require('./package.json').version\")" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ inputs.app-name }}:${{ env.VERSION }}

      - name: Save Docker image as artifact
        run: docker save ${{ inputs.app-name }}:${{ env.VERSION }} -o docker-image.tar

      - uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: ./docker-image.tar
